config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :events do
    # post "/events/:event_id/rsvp", to: "rsvps#create"
    resources :rsvps
  end
  # post "/events/:event_id", to: "rsvps#create"
  # delete "/events/:event_id", to: "rsvps#destroy"

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :rsvps, dependent: :destroy
  has_many :attendees, through: :rsvps, source: :user
  
  scope :past, -> { where('date < ?', Time.now)}
  scope :future, -> { where('date > ?', Time.now)}

  def visible_to?(user)
    if user
      !is_private || (creator_id == user.id || attendees.include?(user))
    else
      !is_private
    end
  end
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :rsvps
  has_many :attended_events, through: :rsvps, source: :event
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    redirect_to events_path unless @event.visible_to?(current_user)
    @attendees = @event.attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)

    if @event.save
      redirect_to @event
    else
      #flash.now(:error) = "Failed to update"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private
  def event_params
    params.require(:event).permit(:title,:location,:date,:is_private)
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    if params[:event][:email]
      invitee = User.find_by(email: params[:event][:email])
    else
      invitee = current_user
    end
  @rsvp = invitee.nil? ? nil : invitee.rsvps.build(event: @event)

    if !@rsvp.nil? && @rsvp.save
      flash[:success] = "Added!"
      redirect_to @event
    else
      flash[:error] = "Not added."
      redirect_to @event
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @event.rsvps.find_by(user_id: current_user.id).destroy
    redirect_to @event
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @created_events = current_user.created_events.all
    @attended_events = current_user.attended_events.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>
  <div class="field">
    <%= form.label :is_private %>
    <%= form.check_box :is_private %>
  </div>
  <div class="field"><%= form.submit %></div>
<% end %>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/index.html.erb
<h1>All Events</h1>

<%= link_to "New event", new_event_path %>

<% @events.includes(:attendees).each do |event| %>
  <div><%= link_to event.title, event if event.visible_to?(current_user) %></div>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>
  <div class="field"><%= form.submit %></div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p>Created by <%= link_to @event.creator.name, user_path(@event.creator_id) %></p>
<p><%= @event.location %></p>
<p><%= @event.date %></p>

<% if user_signed_in? %>
<% if @event.attendees.find_by(id: current_user.id) %>
  <%= form_with model: @event, url: event_rsvp_path(@event, "id"), method: :delete do |form| %>
  <%= form.submit "Un-RSVP" %>
  <% end %>
<% else %>
  <%= form_with model: @event, url: event_rsvps_path(@event), method: :post do |form| %>
  <%= form.submit "RSVP" %>
  <% end %>
<% end %>
<% end %>

<h2>Attending:</h2>
<% if @attendees.empty? %>
<p>None yet</p>
<% else %>
  <% @attendees.each do |attendee| %>
  <div><%= link_to attendee.name, user_path(attendee.id) %></div>
  <% end %>
<% end %>

<% if user_signed_in? && current_user == @event.creator %>
<div class="settings">
  <h3>Settings</h3>
  <div class="field">
    <p>Invite:</p>
    <%= form_with model: @event, url: event_rsvps_path(@event), method: :post do |form| %>
      <%= form.text_field :email %>
      <%= form.submit "Send" %>
    <% end %>
  </div>
  <div class="link"><%= link_to "Edit event", edit_event_path %></div>
  <div class="link"><%= link_to "Delete event", event_path, data: {turbo_method: :delete } %></div>
</div>
<% end %>

<% flash.each do |type, msg| %>
  <div class="flash">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Events", events_path %>
<% if user_signed_in? %>
<%= link_to "#{current_user.name}'s Page", user_path(current_user.id) %>
<%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
<%= link_to "Log In", new_user_session_path %>
<%= link_to "Register", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/users/_event_list.html.erb
<% if list.empty? %>
<p>None</p>
<% else %>
  <% list.each do |event| %>
    <div><%= link_to event.title, event %></div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>

<h2>Created Events:</h2>
<% if @created_events.empty? %>
<p>None</p>
<% else %>
  <% @created_events.each do |event| %>
    <div><%= link_to event.title, event %></div>
  <% end %>
<% end %>

<h2>Upcoming Attending Events:</h2>
<%= render "event_list", list: @attended_events.future %>

<h2>Past Attended Events:</h2>
<%= render "event_list", list: @attended_events.past %>